name: 'coverage'
on:
    pull_request:
        branches:
            - main
     
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - run: |
                cd api
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
