name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MONGODB_URL: "mongodb://localhost:27017/testdb"
    strategy:
         matrix:
             mongodb-version: ['6.0.21']
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
           mongodb-version: ${{ matrix.mongodb-version }}

      - run:  | 
           cd frontend
           npm install
           npm run build --if-present
           npm test

      - run: |
           cd api
           npm install
           npm run build --if-present
           npm run coverage 
