name: Node.js CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
        
permissions:
    checks: write
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
         matrix:
             mongodb-version: ['6.0.21']
    

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
           mongodb-version: ${{ matrix.mongodb-version }}

      - run:  | 
           cd frontend
           npm install
           npm run build --if-present
           npm test

      - run: |
           cd api
           npm install
           npm run build --if-present
           npm test
           npm test -- --coverage

      - name: Check Jest Coverage
        if: github.event_name === 'pull_request' 
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          path: './api/coverage/coverage-summary.json'  # Path to your Jest coverage summary JSON
          coverageThreshold: '80'  # Set the threshold (80% coverage in this case)
          failOnThreshold: true
